// ============================================================
// Ultimate Source Engine - Perception System
//============================================================
//
// Handles AI perception: sight, hearing, and other senses.
// Stimuli are generated by entities with StimulusComponents
// and sensed by entities with PerceptionComponents.
// ============================================================

#pragma once

#include "stdafx.h"
#include "Entity/SystemManager.h"
#include <vector>
#include <memory>

namespace USE {

    // Forward declarations
    class Entity;
    class PerceptionComponent;

    // Types of stimuli
    enum class StimulusType {
        Sight,
        Sound,
        Smell,
        Touch,
        Custom
    };

    // A single stimulus event
    struct Stimulus {
        StimulusType type;
        Entity*      source;        // entity that produced the stimulus
        Vector3      position;      // world position of stimulus
        float        intensity;     // strength (0-1)
        float        radius;        // max distance at which it can be sensed
        float        timestamp;     // world time when it occurred
        // Additional data could be added
    };

    // PerceptionSystem main class
    class PerceptionSystem : public ISystem {
    public:
        PerceptionSystem();
        virtual ~PerceptionSystem();

        // ISystem interface
        void Initialize(EntityManager* entityManager, ComponentManager* componentManager) override;
        void Update(float deltaTime) override;
        void Shutdown() override;

        // Register a stimulus (usually called by StimulusComponent)
        void RegisterStimulus(const Stimulus& stimulus);

    private:
        EntityManager*    m_entityManager;
        ComponentManager* m_componentManager;
        std::vector<Stimulus> m_stimuli;         // stimuli generated this frame
        std::vector<PerceptionComponent*> m_perceptionComponents; // cached list

        // Process all registered stimuli
        void ProcessStimuli();
    };

} // namespace USE